[package]
name = "tracelite"
version = "0.1.0"
edition = "2021"
description = "An alternative to the tracing crate which is specialized for OpenTelemetry traces"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["enable"]
enable = []

[dependencies]
tokio = { version = "1.41", features = ["sync", "rt", "time", "macros"] }
log = { version = "0.4", features=["kv_std", "kv_serde"] }
derive_setters = "0.1"
fastrand = "2.2"
micropb = "0.1"
opentelemetry-micropb = { version = "0.1.0" }