[package]
name = "tracelite"
version = "0.1.3"
edition = "2021"
description = "An alternative to the tracing crate which is specialized for OpenTelemetry traces"
license = "MIT"
repository = "https://github.com/Schmidt-Embedded-Systems-GmbH/tracelite"

# [features]
# default = ["enable", "reqwest", "log", "opentelemetry-micropb"]
# enable = []

[dependencies]
tracelite_macro = "0.1.1"
tokio = { version = "1.41", features = ["sync", "rt", "time", "macros", "net", "rt-multi-thread"] }
futures = "0.3"
log = { version = "0.4", features=["kv_std", "kv_serde"] }
fastrand = "2.2"
micropb = "0.1"
opentelemetry-micropb = { version = "0.1.0" }
reqwest = "0.12"